- name: Connecting and checking print statement
  hosts: frontend
  become: yes
  tasks:
  - debug:
      msg: "Iam debug without name"

- name: Connecting with name debug
  hosts: frontend
  become: yes
  tasks:
    - name: Debug with name
      debug:
        msg: "Iam debug with name"

- name: Instaling and starting nginx
  hosts: frontend
  become: yes
  taks:
    - name: Install nginx
      package:
        name: nginx
        state: present
    - name: Starting nginx
      service: 
        name: nginx
        state: started


