- name: Connecting to server
  hosts: frontend
  become: yes
  tasks:
  - debug:
      msg: "Iam playbook-03"

- name: Installing and starting nginx server
  hosts: frontend
  become: yes
  tasks:
    - name: Install nginx
      package:
        name: nginx
        state: present 

    - name: Starting nginx
      service:
        name: nginx
        state: started