- name: checking variables
  hosts: frontend
  become: yes
  vars:
    COURSE: DevSecOps
    LEARNER: Aditya
    DURATION: "5  months"
    TARGET: Job change
  tasks:
    - debug:
        msg: "Iam{{LEARNER}} Learning {{COURSE}} expected to be completed in {{DURATION}} targeting for {{TARGET}}"

      