- name: Prompt variables
  hosts: local
  connection: local
  vars_prompt:
    - name: username
      prompt: Please enter valid user name
      private: false
    
    - name: password
      prompt: please enter your password here
      private: true
  tasks:
  - debug:
      msg: "Username is {{username}} and password is {{password}}"