- name: Ignore errors handling
  hosts: local
  connection: local
  tasks:
  - name: command error handling
    command: id roboshop
    register: user_output
    ignore_errors: true
    debug:
      msg: "{{user_output}}"