- name: Ignore errors handling
  hosts: local
  connection: local
  tasks:
  - name: command error handling
    command: id roboshop
    register: user_output
    ignore_errors: true

  - name: printing errors
    debug:
      msg: "{{user_output}}"

  - name: add roboshop user
    command: useradd roboshop
    when: user_output.rc != 0