- name: Install nginx through playbook
  hosts: frontend
  tasks:
  - name: Install nginx package
    ansible.builtin.package:
      name: nginx
      state: present

  - name: start nginx service
    service:
      name: nginx
      state: started
      enabled: yes

 