- name: configuring creating - updating R53 records with instances creeate and delete.
  hosts: local
  connection: local
  vars:
    instances: ["mongodb", "redis", "mysql", "frontend"]
    project: "roboshop"
    task_to_perform: "create"
    image_id: ami-0220d79f3f480ecf5
    domain_name: adityabuilds.fun
  tasks:
  - name: create instances.
    amazon.aws.ec2_instance:
      name: "{{project}}-{{item}}"
      instance_type: t3.micro
      image_id: "{{ image_id }}"
      security_groups: 
        - "{{project}}-item"
        - "{{project}}-common"
      wait: false
    loop: "{{instances}}"
    register: ec2_output
    when: task_to_perform == "create"

  - name: updating R53 records
    amazon.aws.route53:
      state: present
      zone: "{{domain_name}}"
      record: "{{item.item}}.{{domain_name}}"
      type: A
      ttl: 1
      value: "{{item.instances[0].private_ip_address}}"
      overwrite: yes
      wait: false
    loop: "{{ec2_output.results}}"
    when: 
    - item.item != 'frontend'
    - task_to_perform == "create"

  - name: updating R53 for frontend
    amazon.aws.route53:
      state: present
      zone: "{{domain_name}}"
      record: "{{item.item}}.{{domain_name}}"
      type: A
      ttl: 1
      value: "{{item.instances[0].public_ip_address}}"
      overwrite: yes
      wait: false
    loop: "{{ec2_output.results}}"
    when: 
    - item.item == 'frontend'
    - task_to_perform == "create"

  - name: Deleting R53 record
    amazon.aws.route53:
      state: absent
      zone: "{{domain_name}}"
      record: "{{item}}.{{domain_name}}"
      type: A
      ttl: 1
      overwrite: yes
      wait: false
    loop: "{{instances}}"
    when: 
    - item.item != 'frontend'
    - task_to_perform == "delete"

  - name: Deleting R53 for frontend
    amazon.aws.route53:
      state: absent
      zone: "{{domain_name}}"
      record: "{{domain_name}}"
      type: A
      ttl: 1
      overwrite: yes
      wait: false
    loop: "{{instances}}"
    when: 
    - item.item == 'frontend'
    - task_to_perform == "delete"

  - name: Deleting Ec2 instances
    amazon.aws.ec2_instance:
      state: absent
      name: "{{project}}-{{item}}"
    loop: "{{instances}}"
    when: task_to_perform == "delete"



